on:
  pull_request:
    branches:
      - master
name: Pull Request Pipeline
jobs:
  pull_request_pipeline:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db
      - uses: symfonycorp/security-checker-action@v4
      - uses: php-actions/composer@v6

      - name: finding vulnerabilities and weaknesses
        run: ./vendor/bin/phpcs --extensions=php,inc,lib,module,info --standard=./vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml ./src/NotificationAPI/NotificationAPI.php
        continue-on-error: true      
